#############################################################################
# Makefile for building: jinyistackedwidget
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 1? 16 14:02:01 2017
# Project:  jinyistackedwidget.pro
# Template: app
# Command: /home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/qmake -o Makefile jinyistackedwidget.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc -lts
CXX           = arm-linux-gnueabihf-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtCore -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtNetwork -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtGui -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtSql -I../../WorkDir/HW_Src/libs/qt-4.8.6/include -I. -Ihwlib -I. -I. -I../../WorkDir/HW_Src/libs/tslib-master/include
LINK          = arm-linux-gnueabihf-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/home/vmuser/WorkDir/HW_Src/libs/tslib-master/lib -L/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib -L ./hwlib -lshm -lQtSql -L/home/vmuser/WorkDir/HW_Src/libs/tslib-master/lib -L/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib -lQtGui -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp moc_widget.cpp \
		qrc_jinyiqrc.cpp
OBJECTS       = main.o \
		widget.o \
		moc_widget.o \
		qrc_jinyiqrc.o
DIST          = ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		jinyistackedwidget.pro
QMAKE_TARGET  = jinyistackedwidget
DESTDIR       = 
TARGET        = jinyistackedwidget

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: jinyistackedwidget.pro  ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtSql.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtCore.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtGui.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile jinyistackedwidget.pro
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtSql.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtCore.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtGui.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile jinyistackedwidget.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/jinyistackedwidget1.0.0 || $(MKDIR) .tmp/jinyistackedwidget1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/jinyistackedwidget1.0.0/ && $(COPY_FILE) --parents widget.h hwlib/libshm.h .tmp/jinyistackedwidget1.0.0/ && $(COPY_FILE) --parents jinyiqrc.qrc .tmp/jinyistackedwidget1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp .tmp/jinyistackedwidget1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/jinyistackedwidget1.0.0/ && (cd `dirname .tmp/jinyistackedwidget1.0.0` && $(TAR) jinyistackedwidget1.0.0.tar jinyistackedwidget1.0.0 && $(COMPRESS) jinyistackedwidget1.0.0.tar) && $(MOVE) `dirname .tmp/jinyistackedwidget1.0.0`/jinyistackedwidget1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/jinyistackedwidget1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: widget.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

compiler_rcc_make_all: qrc_jinyiqrc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_jinyiqrc.cpp
qrc_jinyiqrc.cpp: jinyiqrc.qrc \
		img2/back.png \
		img2/setlog.png \
		img2/backlog.png \
		img2/timesetlog.png \
		img2/beeplog.png \
		img2/icon/35.png \
		img2/icon/36.png
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/rcc -name jinyiqrc jinyiqrc.qrc -o qrc_jinyiqrc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		ui_widget.h \
		hwlib/libshm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

qrc_jinyiqrc.o: qrc_jinyiqrc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_jinyiqrc.o qrc_jinyiqrc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

